CtrlRes/Areas/Admin/Controllers/ComunidadController.cs
using CtrlRes.Data;
using CtrlRes.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CtrlRes.Areas.Admin.Controllers
{

    [Area("Admin")]
    [Authorize]
    public class ComunidadController : Controller
    {
        private readonly ApplicationDbContext _context;
        private Viviendas? vivienda;
        private Privadas? privada;

        public ComunidadController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Comunidad.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comunidad = await _context.Comunidad.Include(m => m.ApplicationUser).FirstOrDefaultAsync(m => m.Id == id);
            if (comunidad == null)
            {
                return NotFound();
            }

            comunidad.Visto = true;
            _context.Update(comunidad);
            await _context.SaveChangesAsync();

            if(comunidad.ApplicationUser.UsuarioTipo == "Propietario") 
            {
                var vivienda_Id =  _context.Propietarios.FirstOrDefault(m => m.Id == comunidad.ApplicationUser.PropOrArr_Id).Vivienda_Id;
                vivienda = _context.Viviendas.FirstOrDefault(m => m.Id == vivienda_Id);
                privada = _context.Privadas.FirstOrDefault(m => m.IdPriv == vivienda.Privada_Id);
            }


            ViewBag.Message = comunidad;
            ViewBag.Vivienda = vivienda;
            ViewBag.Privada = privada;
            return View("Index", await _context.Comunidad.ToListAsync());
        }

        public async Task<IActionResult> Hide(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comunidad = await _context.Comunidad.Include(m => m.ApplicationUser).FirstOrDefaultAsync(m => m.Id == id);
            if (comunidad == null)
            {
                return NotFound();
            }

            comunidad.Oculto = true;
            _context.Update(comunidad);
            await _context.SaveChangesAsync();

            return View("Index", await _context.Comunidad.ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> Reply(int id, string respuesta)
        {
            var comunidad = await _context.Comunidad.FirstOrDefaultAsync(m => m.Id == id);
            if (comunidad == null)
            {
                return NotFound();
            }

            comunidad.Respondido = true;
            comunidad.Respuesta = respuesta;
            comunidad.FechaRegistroRespuesta = DateTime.Now.ToString();
            _context.Update(comunidad);
            await _context.SaveChangesAsync();

            ViewBag.Message = comunidad;
            return View("Index", await _context.Comunidad.ToListAsync());
        }


    }
}

CtrlRes/Areas/Admin/Views/Comunidad/Index.cshtml
@model IEnumerable<Comunidad>

<style>

    .badge:empty {
        display: initial;
    }

    .card-subheader {
        padding: 0.75rem 1.6rem;
    }

    .list-group-item:hover {
        background-color: #f5f5f5;
        cursor: pointer;
    }
</style>

<div class="container mt-5">
    <div class="row">
        <div class="col-md-4">
            <div class="mb-3">
                <span class="badge bg-danger">Queja sobre privada</span>
                <span class="badge bg-warning">Queja sobre la aplicación</span>
                <span class="badge bg-success">Propuesta</span>
            </div>

            <style>
                .list-group-item:hover .dropdown {
                    visibility: visible;
                }

                .dropdown {
                    visibility: hidden;
                }
            </style>

            <ul class="list-group">
                @foreach (var item in Model)
                {
                    if (item.Oculto != true)
                    {
                        string itemClass = "";
                        switch (item.Tipo)
                        {
                            case "Queja sobre privada":
                                itemClass = "list-group-item-danger";
                                break;
                            case "Queja sobre la aplicación":
                                itemClass = "list-group-item-warning";
                                break;
                            case "Propuesta":
                                itemClass = "list-group-item-success";
                                break;
                        }

                        <li class="list-group-item d-flex justify-content-between align-items-center @itemClass @(!item.Visto.HasValue || !item.Visto.Value ? "fw-bold" : "")" onclick="location.href='@Url.Action("Details", "Comunidad", new { id = item.Id })'">
                            @item.Asunto
                            <div class="d-flex align-items-center">
                                <div class="dropdown me-2">
                                    <a class="btn btn-sm btn-outline-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false" onclick="event.stopPropagation();">
                                        ...
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                        <li><a class="dropdown-item" href="@Url.Action("Hide", "Comunidad", new { id = item.Id })">Ocultar mensaje</a></li>
                                    </ul>
                                </div>
                                <span class="badge bg-primary rounded-circle" style="@(!item.Visto.HasValue || !item.Visto.Value ? "" : "visibility: hidden;")"></span>
                            </div>
                        </li>
                    }
                }
            </ul>


        </div>
        <div class="col-md-8">
            @if (ViewBag.Message != null)
            {
                <div class="card mb-3">
                    <div class="card-header" style="background-color: #37322fe3; color: white">
                        <b>Asunto:</b> @ViewBag.Message.Asunto
                    </div>
                    <div class="row">
                        <div class="col-md-4 card-subheader"><b>Usuario:</b> @ViewBag.Message.ApplicationUser.UserName</div>
                        <div class="col-md-4 card-subheader"><b>Privada:</b> @ViewBag.Privada.Nombre</div>
                        <div class="col-md-4 card-subheader"><b>Vivienda:</b> @ViewBag.Vivienda.Numero</div>
                    </div>
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-start mb-3">
                            <div class="rounded p-2 bg-light" style="max-width: 45%; word-wrap: break-word;">@ViewBag.Message.Mensaje</div>
                            <small>@ViewBag.Message.FechaRegistro</small>
                        </div>
                        @if (ViewBag.Message.Respuesta != "--")
                        {
                            <div class="d-flex flex-column align-items-end mb-3">
                                <div class="rounded p-2 bg-secondary text-white" style="max-width: 45%; word-wrap: break-word;">@ViewBag.Message.Respuesta</div>
                                <small>@ViewBag.Message.FechaRegistroRespuesta</small>
                            </div>
                        }
                    </div>
                </div>

                @if (ViewBag.Message.Respuesta == "--")
                {
                    using (Html.BeginForm("Reply", "Comunidad", FormMethod.Post))
                    {
                        int id = ViewBag.Message.Id;

                        @Html.Hidden("Id", id)

                        <div class="input-group mb-3">
                            @Html.TextBox("Respuesta", null, new { @class = "form-control" })
                            <button class="btn btn-outline-secondary" type="submit">Responder</button>
                        </div>
                    }
                }
            }
        </div>
    </div>
</div>