CtrlRes/Areas/Admin/Controllers/EgresosController.cs
using CtrlRes.AccesoDatos.Data.Repository.IRepository;
using CtrlRes.Data;
using CtrlRes.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CtrlRes.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class EgresosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EgresosController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var egresos = _context.Egresos.ToList();

            ViewBag.Egresos = egresos;

            return View();
        }


        //Agregar nueva tarjeta Catalogo
        [HttpGet]
        [Authorize(Roles = "Administrador, Creador/Editor, Creador")]
        public IActionResult Create()
        {

            var PrivadasList = _context.Privadas.Select(x => new SelectListItem
            {
                Text = x.Nombre,
                Value = x.IdPriv,
            });

            ViewBag.Privadas = PrivadasList;

            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        [Authorize(Roles = "Administrador, Creador/Editor, Creador")]
        public IActionResult Create(Egresos egresos)
        {

            if (ModelState.IsValid)
            {

                TimeZoneInfo tz = TimeZoneInfo.FindSystemTimeZoneById("America/Mexico_City");
                DateTimeOffset fechaRegistroMx = TimeZoneInfo.ConvertTime(DateTimeOffset.UtcNow, tz);
                egresos.FechaRegistro = fechaRegistroMx.ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss.fffffffK");

                _context.Egresos.Add(egresos);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }

            return View(egresos);

        }
    }
}

CtrlRes/Areas/Admin/Views/Egresos/Create.cshtml
@model CtrlRes.Models.Egresos

@{
    ViewData["Title"] = "Registrar Egreso";
}

<link rel="stylesheet" href="~/css/formRyE.css" />

<div class="page-wrapper p-t-45 p-b-50">
    <div class="wrapper wrapper--w790">
        <div class="card card-5">
            <div class="card-heading">
                <h2 class="title">REGISTRAR UN EGRESO</h2>
            </div>
            <div class="card-body">
                <form id="registerForm" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>

                    <div class="form-row">
                        <label asp-for="Monto" class="name">Monto:</label>
                        <div class="value">
                            <input asp-for="Monto" type="number" step="0.01" class="form-control" style="font-size:18px" />
                        </div>
                        <span asp-validation-for="Monto" class="text-danger"></span>
                    </div>

                    <div class="form-row">
                        <label asp-for="Concepto" class="name">Concepto:</label>
                        <div class="value">
                            <input asp-for="Concepto" class="form-control" style="font-size:18px" />
                        </div>
                        <span asp-validation-for="Concepto" class="text-danger"></span>
                    </div>

                    <div class="form-row">
                        <label asp-for="Motivo" class="name">Motivo:</label>
                        <div class="value">
                            <input asp-for="Motivo" class="form-control"  style="font-size:18px" />
                        </div>
                        <span asp-validation-for="Motivo" class="text-danger"></span>
                    </div>

                    <div class="form-row ">
                        <label class="name">Tipo de egreso:</label>
                        <div class="value d-flex justify-content-end">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="tipo" id="propietario" value="Mantenimiento">
                                <label class="form-check-label" for="propietario">Mantenimiento</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="tipo" id="arrendatario" value="Otro">
                                <label class="form-check-label" for="arrendatario">Otro</label>
                            </div>
                        </div>
                    </div>

                    <input asp-for="Tipo" type="hidden" id="tipo_seleccionado">

                    @*//*@

                    <div class="form-row" id="selector_privada" disabled>
                        <div class="name">Privada:</div>


                        <div class="value">
                            <div class="rs-select2 js-select-simple select--no-search">
                                <select asp-for="Privada_Id" asp-items="@ViewBag.Privadas" id="selector_2" class="form-control" aria-required="true">
                                    <option disabled selected>Seleccione al propietario</option>
                                </select>
                                <div class="select-dropdown"></div>
                                <span asp-validation-for="Privada_Id" class="text-danger"></span>
                            </div>
                        </div>

                    </div>

                    @*///*@


                    <div class="form-group row">
                        <div class="col-12">
                            <div class="row">
                                <div class="col">
                                    <button type="submit" class="btn btn-primary form-control" style="font-size:20px">Agregar</button>
                                    &nbsp;
                                </div>
                                <div class="col">
                                    <a asp-area="Admin" asp-controller="Egresos" asp-action="Index" class="btn btn-success form-control" style="font-size:20px">Volver a la lista</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>

    $(document).ready(function () {

        const tipo_input = document.getElementById('tipo_seleccionado');
        const checkboxes = document.querySelectorAll('input[type=radio][name=tipo]');

        checkboxes.forEach((checkbox) => {
            checkbox.addEventListener('change', function () {
                tipo_input.value = this.value;

                if (tipo_input.value == "Mantenimiento") {

                    $("#tipo_seleccionado").val("Mantenimiento");

                }
                if (tipo_input.value == "Otro") {

                    $("#tipo_seleccionado").val("Otro");
                }

            });
        });

    });
</script>

CtrlRes/Areas/Admin/Views/Egresos/Index.cshtml
@model CtrlRes.Models.Egresos

@{
    ViewData["Title"] = "Egresos";
    Layout = "~/Views/Shared/_Layout.cshtml";
    //Layout = null;
}

@section styles {
    <!--Bootstrap 5 & Datatables CSS-->

    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/dataTables.bootstrap5.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.3.6/css/buttons.bootstrap5.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.5/dist/sweetalert2.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/TablaCatalogo.css" />

}

@section scriptsup {

    <!--Bootstrap 5 & Datatables JS-->
    @*<script src="https://code.jquery.com/jquery-3.5.1.js"></script>*@
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.bootstrap5.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.colVis.min.js"></script>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.5/dist/sweetalert2.all.min.js"></script>
}


<div id="vista-tabla1" class="mt-5">

    <table id="Tabla" class="table display cell-border table-bordered" style="width:100%">
        <thead>
            <tr class="table-custom"><th colspan="8" style="text-align:center"><h3 class="text-center">Egresos</h3></th></tr>
            <tr class="table-secondary">
                <th>Id</th>
                <th>Tipo</th>
                <th>Concepto</th>
                <th>Monto</th>
                <th>Motivo</th>
                <th>Fecha</th>
                <th>Privada ID</th>
                <th class="not-export-col" style="text-align:center">Acciones</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>Filter..</th>
                <th>Filter..</th>
                <th>Filter..</th>
                <th>Filter..</th>
                <th>Filter..</th>
                <th>Filter..</th>
                <th>Filter..</th>
                <th>Filter..</th>
            </tr>
        </tfoot>
        <tbody>

            @foreach (var egresos in ViewBag.Egresos)
            {
                <tr>
                    <td>@egresos.Id</td>
                    <td>@egresos.Tipo</td>
                    <td>@egresos.Concepto</td>
                    <td>@egresos.Monto</td>
                    <td>@egresos.Motivo</td>
                    <td>@egresos.FechaRegistro</td>
                    <td>@egresos.Privada_Id</td>
                    <td class="text-center">
                        <a href='/Admin/Egresos/Edit/@egresos.Id' class='btn btn-success text-white' style='cursor:pointer; '>
                            <i class='fas fa-edit'></i> Editar
                        </a>
                        <button type="button" class="borrar btn btn-danger text-white" style='cursor:pointer; ' data-id="@egresos.Id" data-url="/Admin/Egresos/Delete/">
                            <i class='fas fa-trash-alt'></i> Borrar
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section scriptsdown {

    <script src="~/js/TablaCatalogos.js"></script>
}